Clean redundant DNS records
openstack-k8s-operators/ovn-operator pull request #245
Opened 2024-03-11 17:37 UTC by averdagu

For each replica of each DB service (NB/SB) ovn-operator will create a DNSData CR. This commit modifies this and each DB service will have each own DNSData CR (ovnsb-cluster, ovnnb-cluster) and this CR will contain all the each pod IP.

Jira: OSPRH-3628

2024-03-15 16:11 UTC, booxter requested changes
since you have to rebase, please also change the variable names; but otherwise I think it's good to go

2024-03-15 16:11 UTC, booxter commented on api/v1beta1/ovndbcluster_types.go
> +	NBDBDnsName = "ovnnb-cluster"
DNS: https://google.github.io/styleguide/go/decisions#initialisms should retain the original upper case for abbreviations (unless it's unexported and at the start of the variable name, so e.g. dnsList is fine for a variable).

2024-03-20 12:39 UTC, karelyatin commented on controllers/ovndbcluster_controller.go
> +			dnsDataName,
Instead of dnsDataName i think we can just use serviceName and avoid all the logic above.

2024-03-25 16:14 UTC, booxter commented
recheck

2024-03-26 10:33 UTC, averdagu commented
recheck

2024-03-28 06:07 UTC, karelyatin commented
/test functional

2024-03-28 07:48 UTC, karelyatin commented
recheck cert-manager issue fixed

2024-03-28 09:05 UTC, karelyatin approved these changes
/lgtm

2024-03-28 11:00 UTC, merged